name: Petr
favicon: null
layout_spectrum: 0.72524
typography_spectrum: 0.7938009982462972
title: The Buro
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.027197128161787987
  lightness: 0.03988218563608825
  saturation: 0.01667624549008906
  rhythmicContrast: 0.20796787412837148
purpose: []
